const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS, PUT, DELETE",
};

const IFOOD_API = "https://merchant-api.ifood.com.br";
const IFOOD_AUTH_URL = "https://merchant-api.ifood.com.br/authentication/v1.0/oauth/token";

function sbHeaders() {
  return {
    "apikey": Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
    "Authorization": `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`,
    "Content-Type": "application/json",
    "Prefer": "return=representation",
  };
}
function sbUrl(p: string) { return `${Deno.env.get("SUPABASE_URL")}/rest/v1${p}`; }

async function safeJson(res: Response) {
  try { const t = await res.text(); return t ? JSON.parse(t) : null; }
  catch { return null; }
}

async function getAccessToken() {
  const clientId = Deno.env.get("IFOOD_CLIENT_ID");
  const clientSecret = Deno.env.get("IFOOD_CLIENT_SECRET");

  const res = await fetch(sbUrl("/ifood_tokens?select=*&order=created_at.desc&limit=1"), { headers: sbHeaders() });
  const tokens = await safeJson(res);

  if (!Array.isArray(tokens) || tokens.length === 0)
    throw new Error("NOT_AUTHENTICATED: Configure a autenticação iFood primeiro.");

  const token = tokens[0];
  const isExpired = new Date(token.expires_at) < new Date();
  if (!isExpired) return token.access_token;

  // Refresh
  const rRes = await fetch(IFOOD_AUTH_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ grantType: "refresh_token", clientId, clientSecret, refreshToken: token.refresh_token }),
  });
  const data = await safeJson(rRes);
  if (!rRes.ok || !data?.accessToken)
    throw new Error("NOT_AUTHENTICATED: Token expirado. Reautentique o iFood.");

  await fetch(sbUrl(`/ifood_tokens?id=eq.${token.id}`), {
    method: "PATCH",
    headers: sbHeaders(),
    body: JSON.stringify({
      access_token: data.accessToken,
      refresh_token: data.refreshToken || token.refresh_token,
      expires_at: new Date(Date.now() + (data.expiresIn || 3600) * 1000).toISOString(),
      updated_at: new Date().toISOString(),
    }),
  });
  return data.accessToken;
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const accessToken = await getAccessToken();

    // ── Validate action: cross-check pending_orders against live iFood API ──
    const body = req.method === "POST" ? (await req.json().catch(() => null)) : null;
    if (body?.action === "validate" && Array.isArray(body.ids) && body.ids.length > 0) {
      const VALID_STATUSES = new Set(["ACCEPTED", "DISPATCHED"]);
      const ids: string[] = body.ids;

      const results = await Promise.all(
        ids.map(async (id: string) => {
          try {
            // Bypass API check for fake test orders generated by Admin panel
            if (id.startsWith("TEST-")) {
              return { id, valid: true };
            }

            const oRes = await fetch(`${IFOOD_API}/order/v1.0/orders/${id}`, {
              headers: { "Authorization": `Bearer ${accessToken}` },
            });
            // 404/410 means order was archived/concluded -> invalid
            if (oRes.status === 404 || oRes.status === 410) {
              return { id, valid: false };
            }
            if (oRes.status !== 200) { await oRes.text(); return { id, valid: true }; } // assume valid on unknown error so we don't accidentally purge
            
            const o = await safeJson(oRes);
            const rawStatus = o?.orderStatus || o?.status || o?.ORDERSTATUS || o?.STATUS || o?.order_status || "";
            const status = String(rawStatus).toUpperCase().trim();
            
            // terminal statuses
            const CANCELLED_S = new Set(["CANCELLED", "CANCELLATION_REQUESTED", "CONSUMER_CANCELLED", "CAR", "CAN"]);
            const isCancelled = CANCELLED_S.has(status);
            const isConcluded = status === "CONCLUDED" || status === "DELIVERED" || status === "COR" || status === "CDD";
            
            // Do not treat naturally cancelled as invalid or else it gets purged silently.
            // We want it visually staying in DB with status=CANCELLED so the Motoboy App UI can show it.
            return { id, valid: (isCancelled || !isConcluded) };
          } catch {
            return { id, valid: true }; // don't purge on throw
          }
        })
      );

      const validIds = results.filter(r => r.valid).map(r => r.id);
      const staleIds = results.filter(r => !r.valid).map(r => r.id);

      // Delete stale orders from pending_orders immediately
      if (staleIds.length > 0) {
        await fetch(sbUrl(`/pending_orders?id=in.(${staleIds.join(",")})`), {
          method: "DELETE",
          headers: sbHeaders(),
        });
      }

      return new Response(JSON.stringify({ validIds, staleIds }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // ── check_route_orders: poll status of in-route orders directly ───────────
    // Calls GET /order/v1.0/orders/{id} for each in-route order to check its current status.
    // Mirrors the same approach used for cancellation detection.
    if (body?.action === "check_route_orders" && Array.isArray(body.orderIds) && body.orderIds.length > 0) {
      // Official documented statuses from iFood API docs
      const ACTIVE_S = new Set([
        "PENDING", "CONFIRMED", "ASSIGNED_DRIVER",
        "GOING_TO_ORIGIN", "ARRIVED_AT_ORIGIN",
        "DISPATCHED", "ARRIVED_AT_DESTINATION",
        "ACCEPTED", // legacy / v1 code
      ]);
      const CANCELLED_S = new Set([
        "CANCELLED", "CANCELLATION_REQUESTED", "CONSUMER_CANCELLED", "CAR", "CAN",
      ]);
      const orderIds: string[] = body.orderIds;
      console.log(`[check_route_orders] Checking ${orderIds.length} order(s):`, orderIds);

      const results = await Promise.all(
        orderIds.map(async (id: string) => {
          try {
            const oRes = await fetch(`${IFOOD_API}/order/v1.0/orders/${id}`, {
              headers: { "Authorization": `Bearer ${accessToken}` },
            });
            console.log(`[check_route_orders] order ${id} → HTTP ${oRes.status}`);

            if (oRes.status === 404 || oRes.status === 410) {
              // iFood returns 404 for orders not found or already archived after conclusion
              console.log(`[check_route_orders] order ${id} → 404/410, treating as CONCLUDED`);
              return { id, terminal: true, cancelled: false, status: "NOT_FOUND" };
            }
            if (oRes.status !== 200) {
              const errText = await oRes.text();
              console.log(`[check_route_orders] order ${id} → unexpected ${oRes.status}: ${errText}`);
              return { id, terminal: false, cancelled: false, status: `HTTP_${oRes.status}` };
            }

            const o = await oRes.json();
            // Try all known field names for status (iFood API is inconsistent across versions)
            const rawStatus = o?.orderStatus || o?.status || o?.ORDERSTATUS || o?.STATUS || o?.order_status || "";
            const status = String(rawStatus).toUpperCase().trim();
            console.log(`[check_route_orders] order ${id} → status: "${status}"`);

            const isCancelled = CANCELLED_S.has(status);
            // Per iFood docs: only "CONCLUDED" means the order is done.
            // NEVER treat empty/unknown status as terminal — that causes active orders to be removed!
            const isTerminal = status === "CONCLUDED" || status === "DELIVERED" || isCancelled;
            return { id, terminal: isTerminal, cancelled: isCancelled, status };
          } catch (err: any) {
            console.error(`[check_route_orders] order ${id} → error:`, err?.message);
            return { id, terminal: false, cancelled: false, status: "ERROR" };
          }
        })
      );

      console.log(`[check_route_orders] results:`, JSON.stringify(results));
      return new Response(JSON.stringify({ results }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }



    // ─ Fetch merchant list for store address (independent of order events) ───
    let topLevelMerchantAddress: string | null = null;
    let topLevelStoreLat: number | null = null;
    let topLevelStoreLng: number | null = null;
    try {
      const mRes = await fetch(`${IFOOD_API}/merchant/v1.0/merchants`, {
        headers: { "Authorization": `Bearer ${accessToken}` },
      });
      const mBody = await safeJson(mRes) || [];
      const merchants = Array.isArray(mBody) ? mBody : (mBody.merchants || []);
      const firstId = merchants[0]?.id;
      
      if (firstId) {
        // Fetch detailed merchant data to actually get the address field
        const detailRes = await fetch(`${IFOOD_API}/merchant/v1.0/merchants/${firstId}`, {
          headers: { "Authorization": `Bearer ${accessToken}` },
        });
        const first = await safeJson(detailRes);
        if (first) {
          // Try every known field name for the address
          const mAddr = first.address || first.mainAddress || first.corporateAddress || {};
          const formatted = [
            mAddr.streetName || mAddr.street || mAddr.logradouro || "",
            mAddr.streetNumber || mAddr.number || mAddr.numero || "",
            mAddr.complement || mAddr.complemento || "",
            mAddr.neighborhood || mAddr.district || mAddr.bairro || "",
            mAddr.city || mAddr.cidade || mAddr.locality || "",
            mAddr.state || mAddr.estado || mAddr.province || "",
          ].filter(Boolean).join(", ");
          
          if (formatted) topLevelMerchantAddress = formatted;
          const lat = mAddr.latitude || mAddr.coordinates?.latitude || first.latitude;
          const lng = mAddr.longitude || mAddr.coordinates?.longitude || first.longitude;
          if (lat) { topLevelStoreLat = lat; topLevelStoreLng = lng; }
        }
      }
    } catch (e: any) { console.log('[merchant-api] error:', e?.message); }

    // Poll events
    const eventsRes = await fetch(`${IFOOD_API}/events/v1.0/events:polling`, {
      headers: { "Authorization": `Bearer ${accessToken}` },
    });

    let events: any[] = [];
    if (eventsRes.status === 200) {
      const parsed = await safeJson(eventsRes);
      if (Array.isArray(parsed)) events = parsed;
    } else {
      await eventsRes.text();
    }

    // Statuses we want to show in the restaurant queue
    // Only show orders that the store has ACCEPTED for own delivery.
    // We include CONFIRMED, PREPARING, READY_TO_PICKUP so they don't disappear when the restaurant starts preparing them.
    const SHOW_STATUSES = [
      "ACCEPTED", 
      "CONFIRMED", 
      "PREPARATION_STARTED", 
      "PREPARING", 
      "READY_TO_PICKUP", 
      "DISPATCHED"
    ];
    const TERMINAL_STATUSES = new Set(["CONCLUDED", "CANCELLED", "CANCELLATION_REQUESTED", "CONSUMER_CANCELLED"]);
    const CANCELLED_STATUSES = new Set(["CANCELLED", "CANCELLATION_REQUESTED", "CONSUMER_CANCELLED"]);
    const OWN_DELIVERY_MODES = ["DEFAULT", "RESTAURANT", "OWN", "PADRAO", "MERCHANT"];

    // Comprehensive iFood event code map (v1 + v2 codes)
    const evCodeMap: Record<string, string> = {
      // Store accepted the order → show in queue
      "ACK": "ACCEPTED", "ACCEPTED": "ACCEPTED",
      // Placed by customer but NOT yet accepted by store → do NOT show
      "PLC": "PLACED", "PLACED": "PLACED",
      // Restaurant confirmed to kitchen → we SHOULD show it so motoboy can be assigned
      "CFM": "CONFIRMED", "CONFIRMED": "CONFIRMED",
      // Ready to pickup
      "RTP": "READY_TO_PICKUP", "READY_TO_PICKUP": "READY_TO_PICKUP",
      "ORDER_CREATED": "PLACED",
      // Dispatched / out for delivery
      "DSP": "DISPATCHED", "DISPATCHED": "DISPATCHED",
      "DDCR": "DISPATCHED", // Driver Dispatched – Consumer Route
      "DDCS": "DISPATCHED", // Driver Dispatched – Consumer Start
      "PREP": "PREPARING", // Preparing
      "PREPARATION_STARTED": "PREPARING",
      "BADI": "DISPATCHED", // Bag dispatched
      "ORDER_DISPATCHED": "DISPATCHED",
      // Terminal – concluded
      "CON": "CONCLUDED", "COR": "CONCLUDED", "CONCLUDED": "CONCLUDED", "CDD": "CONCLUDED",
      "ORDER_CONCLUDED": "CONCLUDED", "DELIVERED": "CONCLUDED",
      // Terminal – cancelled
      "CAN": "CANCELLED", "CANCELLED": "CANCELLED",
      "CAR": "CANCELLED", // Cancelled by Restaurant
      "CAC": "CANCELLED", // Cancelled (another variant)
      "CANCELLATION_REQUESTED": "CANCELLATION_REQUESTED",
      "CONSUMER_CANCELLED": "CONSUMER_CANCELLED",
    };
    const orders: any[] = [];
    const concludedOrders: any[] = [];
    const cancelledOrderIds: string[] = [];
    const debug: any[] = [];
    const eventIdsToAck: string[] = [];
    const processedOrderIds = new Set<string>();

    for (const ev of events) {
      const orderId = ev.orderId;
      // Ack events without orderId
      if (!orderId) { eventIdsToAck.push(ev.id); continue; }
      // Deduplicate: skip if already handled as TERMINAL (terminal events always win)
      if (processedOrderIds.has(orderId)) { eventIdsToAck.push(ev.id); continue; }

      try {
        const oRes = await fetch(`${IFOOD_API}/order/v1.0/orders/${orderId}`, {
          headers: { "Authorization": `Bearer ${accessToken}` },
        });

        if (oRes.status !== 200) {
          await oRes.text();
          eventIdsToAck.push(ev.id);
          // iFood often returns 404/410 for concluded/archived orders.
          // Fall back to event code alone so we still handle terminal statuses.
          const evCode = (ev.code || ev.fullCode || ev.type || "").toUpperCase();
          const fallbackStatus = evCodeMap[evCode] || "";
          if (CANCELLED_STATUSES.has(fallbackStatus)) {
            cancelledOrderIds.push(orderId);
            processedOrderIds.add(orderId);
            debug.push({ evCode, status: fallbackStatus, orderId, note: "fallback from non-200" });
          } else if (fallbackStatus === "CONCLUDED") {
            concludedOrders.push({ id: orderId, displayId: orderId.slice(0, 8), customerName: "Cliente", address: "", lat: 0, lng: 0, total: 0 });
            processedOrderIds.add(orderId);
            debug.push({ evCode, status: fallbackStatus, orderId, note: "fallback from non-200" });
          }
          continue;
        }

        const o = await safeJson(oRes);
        const id = o?.id || o?.ID;
        if (!id) { eventIdsToAck.push(ev.id); continue; }

        let status = (o.orderStatus || o.ORDERSTATUS || "").toUpperCase();

        // Map event codes → canonical status (covers all known iFood v1 + v2 codes)
        if (!status) {
          const evCode = (ev.code || ev.fullCode || ev.type || "").toUpperCase();
          status = evCodeMap[evCode] || "";
        }
        const delivery = o.delivery || o.DELIVERY || {};
        const deliveryMode = (delivery.mode || delivery.MODE || delivery.deliveryBy || delivery.DELIVERYBY || "").toUpperCase();
        const orderType = (o.orderType || o.ORDERTYPE || "DELIVERY").toUpperCase();

        // Always log for debug
        debug.push({ evCode: ev.code || ev.fullCode, status, deliveryMode, orderType, orderId });

        // Terminal orders — ack immediately
        if (TERMINAL_STATUSES.has(status)) {
          eventIdsToAck.push(ev.id);
          processedOrderIds.add(orderId); // mark as terminal so non-terminal events below skip it

          // Extract basic order info for frontend sync
          const c = o.customer || o.CUSTOMER || {};
          const d = o.delivery || o.DELIVERY || {};
          const da = d.deliveryAddress || d.DELIVERYADDRESS || {};
          const dc = da.coordinates || da.COORDINATES || {};
          const t = o.total || o.TOTAL || {};
          const addrStr = [da.streetName || "", da.streetNumber || "", da.neighborhood || "", da.city || ""].filter(Boolean).join(", ");

          if (CANCELLED_STATUSES.has(status)) {
            cancelledOrderIds.push(orderId);
          } else {
            // CONCLUDED: return full summary so frontend can save to confirmed_orders
            concludedOrders.push({
              id: orderId,
              displayId: o.displayId || o.DISPLAYID || orderId.slice(0, 8),
              customerName: c.name || c.NAME || "Cliente",
              address: addrStr || "Endereço não disponível",
              lat: dc.latitude || dc.LATITUDE || 0,
              lng: dc.longitude || dc.LONGITUDE || 0,
              total: t.orderAmount || t.ORDERAMOUNT || 0,
              deliveryFee: Math.round(Number(t.deliveryFee || t.DELIVERYFEE || o.deliveryFee || o.DELIVERYFEE || d.fee || d.FEE || 0) * 100),
            });
          }
          continue;
        }

        // Status not in our show list (PLACED, unknown codes, etc.)
        // ACKNOWLEDGE and skip — do not let them pile up in the events queue.
        // New events will be fired when the order transitions to ACCEPTED/DISPATCHED.
        if (!SHOW_STATUSES.includes(status)) {
          console.log(`[ifood-orders] Skipped ${orderId} because status ${status} is not in SHOW_STATUSES`);
          eventIdsToAck.push(ev.id);
          continue;
        }

        // Ack-and-skip non-own-delivery orders
        if (orderType === "TAKEOUT" || orderType === "PICKUP") {
          console.log(`[ifood-orders] Skipped ${orderId} because orderType is ${orderType}`);
          eventIdsToAck.push(ev.id); continue;
        }
        if (deliveryMode && !OWN_DELIVERY_MODES.some(m => deliveryMode.includes(m))) {
          console.log(`[ifood-orders] Skipped ${orderId} because deliveryMode ${deliveryMode} is not in OWN_DELIVERY_MODES. Raw dump: ${JSON.stringify(delivery)}`);
          eventIdsToAck.push(ev.id); continue;
        }

        // This order is ready to show — ack and mark processed (non-terminal, won't block a later terminal event)
        eventIdsToAck.push(ev.id);

        const customer = o.customer || o.CUSTOMER || {};
        const address = delivery.deliveryAddress || delivery.DELIVERYADDRESS || {};
        const coords = address.coordinates || address.COORDINATES || {};
        const totals = o.total || o.TOTAL || {};
        // payments can be an object { methods: [] } OR an array depending on API version
        const paymentsObj = o.payments || o.PAYMENTS || {};
        const paymentMethods = Array.isArray(paymentsObj) ? paymentsObj : (paymentsObj.methods || []);
        const itemsArr = o.items || o.ITEMS || [];

        const displayId = o.displayId || o.DISPLAYID || id.slice(0, 8);
        // iFood localizer: customer.phone.localizer is an 8-digit code displayed as XXXX XXXX
        const rawLocalizer = customer.phone?.localizer || customer.PHONE?.LOCALIZER || "";
        const localizador = rawLocalizer.length === 8
          ? `${rawLocalizer.slice(0, 4)} ${rawLocalizer.slice(4)}`
          : rawLocalizer || displayId;
        const addressStr = [
          address.streetName || address.STREETNAME || "",
          address.streetNumber || address.STREETNUMBER || "",
          address.complement || address.COMPLEMENT || "",
          address.neighborhood || address.NEIGHBORHOOD || "",
          address.city || address.CITY || "",
          address.state || address.STATE || "",
        ].filter(Boolean).join(", ") || "Endereço não disponível";

        const merchant = o.merchant || o.MERCHANT || {};
        const mAddr = merchant.address || merchant.ADDRESS || {};
        const mCoords = merchant.address?.coordinates || {};
        const merchantAddress = [
          mAddr.streetName || mAddr.STREETNAME || "",
          mAddr.streetNumber || mAddr.STREETNUMBER || "",
          mAddr.neighborhood || mAddr.NEIGHBORHOOD || "",
          mAddr.city || mAddr.CITY || "",
          mAddr.state || mAddr.STATE || "",
        ].filter(Boolean).join(", ");

        // Capture merchant location once (same for all orders)
        if (merchantAddress && !topLevelMerchantAddress) topLevelMerchantAddress = merchantAddress;
        if (mCoords.latitude && !topLevelStoreLat) {
          topLevelStoreLat = mCoords.latitude;
          topLevelStoreLng = mCoords.longitude;
        }

        orders.push({
          id, displayId, localizador,
          customerName: customer.name || customer.NAME || "Cliente",
          customerPhone: customer.phone?.number || customer.PHONE?.NUMBER || "",
          address: addressStr,
          lat: coords.latitude || coords.LATITUDE || 0,
          lng: coords.longitude || coords.LONGITUDE || 0,
          total: totals.orderAmount || totals.ORDERAMOUNT || 0,
          deliveryFee: Math.round(Number(totals.deliveryFee || totals.DELIVERYFEE || o.deliveryFee || o.DELIVERYFEE || delivery.fee || delivery.FEE || 0) * 100),
          paymentMethod: paymentMethods[0]?.type || paymentMethods[0]?.method || "ONLINE",
          items: itemsArr.map((i: any) => `${i.quantity || i.QUANTITY}x ${i.name || i.NAME}`).join(", ") || "",
          status,
          createdAt: o.createdAt || o.CREATEDAT,
          deliveryCode: delivery.pickupCode || delivery.PICKUPCODE || "",
          raw: o,
        });
      } catch (err) {
        console.error(`Error fetching order ${orderId}:`, err);
        eventIdsToAck.push(ev.id);
      }
    }

    // Acknowledge only the events we've fully processed
    if (eventIdsToAck.length > 0) {
      await fetch(`${IFOOD_API}/events/v1.0/events/acknowledgment`, {
        method: "POST",
        headers: { "Authorization": `Bearer ${accessToken}`, "Content-Type": "application/json" },
        body: JSON.stringify(eventIdsToAck.map((i: string) => ({ id: i }))),
      });
    }

    // ─ Persist new orders in DB (survives refreshes / logouts) ───────────────
    if (orders.length > 0) {
      const rows = orders.map((o: any) => ({
        id: o.id,
        display_id: o.displayId,
        localizador: o.localizador,
        customer_name: o.customerName,
        customer_phone: o.customerPhone,
        customer_address: o.address,
        lat: o.lat,
        lng: o.lng,
        total: o.total,
        payment_method: o.paymentMethod,
        items: o.items,
        status: o.status,
        created_at: o.createdAt,
        delivery_code: o.deliveryCode,
        raw_data: o.raw,
        received_at: new Date().toISOString(),
      }));
      await fetch(sbUrl("/pending_orders"), {
        method: "POST",
        headers: { ...sbHeaders(), "Prefer": "resolution=merge-duplicates,return=minimal" },
        body: JSON.stringify(rows),
      });
    }

    // ─ Remove concluded from pending queue ────────────────────
    const toRemove = concludedOrders.map((o: any) => o.id);
    if (toRemove.length > 0) {
      await fetch(sbUrl(`/pending_orders?id=in.(${toRemove.join(",")})`), {
        method: "DELETE",
        headers: sbHeaders(),
      });
    }

    // ─ Keep cancelled orders in DB, but mark status as CANCELLED ────────────────────
    if (cancelledOrderIds.length > 0) {
      await fetch(sbUrl(`/pending_orders?id=in.(${cancelledOrderIds.join(",")})`), {
        method: "PATCH",
        headers: sbHeaders(),
        body: JSON.stringify({ status: "CANCELLED" }),
      });
    }

    // ─ Publish order status events so ALL clients get notified via Realtime ──
    // This ensures in-route orders also get handled by drivers who didn't poll.
    const statusEvents: any[] = [
      ...concludedOrders.map((o: any) => ({
        order_id: o.id,
        status: "concluded",
        order_data: o,
      })),
      ...cancelledOrderIds.map((id: string) => ({
        order_id: id,
        status: "cancelled",
        order_data: null,
      })),
    ];
    if (statusEvents.length > 0) {
      await fetch(sbUrl("/order_status_events"), {
        method: "POST",
        headers: { ...sbHeaders(), "Prefer": "resolution=merge-duplicates,return=minimal" },
        body: JSON.stringify(statusEvents),
      });
    }

    // ─ Clean up old status events (> 2h) to prevent table growth ──────────
    const twoHoursAgo = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();
    await fetch(sbUrl(`/order_status_events?created_at=lt.${twoHoursAgo}`), {
      method: "DELETE",
      headers: sbHeaders(),
    });


    return new Response(JSON.stringify({
      orders,
      concludedOrders,
      cancelledOrderIds,
      merchantAddress: topLevelMerchantAddress,
      storeLat: topLevelStoreLat,
      storeLng: topLevelStoreLng,
      eventsCount: events.length,
      debug,
    }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error: any) {
    const message = error?.message || "Unknown error";
    const isAuthError = message.includes("NOT_AUTHENTICATED");
    return new Response(JSON.stringify({ error: message, orders: [], needsAuth: isAuthError }), {
      status: isAuthError ? 200 : 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
